root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server"
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = ["./tailwind_builder.go"]  # Add the Tailwind builder Go file here
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = true
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[runner]
  args = ["./tmp/main"]
  break_before = ""
  breakpoint = false
  clear_screen = true
  color = ""
  debug = true
  directory = ""
  dir_filter = []
  env = []
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = []
  exit_code = 0
  exclude_unchanged = false
  filter = []
  go_args = []
  include_dir = []
  include_ext = []
  include_file = []
  log = ""
  main_dir = ""
  main_file = ""
  new_terminal = false
  not_env = []
  run_dir = "."
  runner = ""
  runner_args = []
  stderr = ""
  stdout = ""
  tmp_dir = ""
  watch_ext = ["go", "tpl", "tmpl", "html", "sh"]
  watch_dir = ["."]
  watch_poll_interval = 0
  write = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
